### ISSUE TITLE
FTB Utilities Fake Player

### ISSUE THREAD

**Issue by SolarEclipz** [McJtyMods/MeeCreeps#27]
My Issue is the fact that if I have a claim chunk MeeCreeps sits idle and does not do anything, unless I remove the claimed chunk. Is it possible to add fake player settings or what not so MeeCreeps is usable while in my claimed chunk? Or am I missing something completely here?

I'm playing All The Mods 3 in a MP server. 

Thank you

**Comment by McJty** [comment]
MeeCreeps use a fake player already. You have to ask on FTB Utilities side how to solve it to allow fake player interaction in those chunks

**Comment by McJty** [comment]
Apparently it is a bug in FTB Utilities
