### ISSUE TITLE
Meecreep server crash 1.12

### ISSUE THREAD

**Issue by ktole1999** [McJtyMods/MeeCreeps#44]
latest DW20 pack v1.11
https://gist.github.com/ktole1999/454b7dd53571cd0d378ca51cca3ff9b2

any help is greatly appreciated.

**Comment by McJty** [comment]
I need more information. What are you doing exactly?

**Comment by ktole1999** [comment]
sorry, the server was empty. no recent logins or logouts.

**Comment by McJty** [comment]
Not much I can do then I'm afraid

**Comment by ktole1999** [comment]
ok thanks for your time.

**Comment by McJty** [comment]
You have logs?

**Comment by Shybella** [comment]
https://pastebin.com/raw/cKdemME7

Fix: Delete MeeCreepsData.dat

**Comment by McJty** [comment]
Hmm interesting. I do see you have sponge however. I wonder if this is an issue with sponge

**Comment by Shybella** [comment]
Yeap, very well could be. It also seems load/unload dimensions.

**Comment by Virtue-Rabbit** [comment]
Spawned a meecreep to make stairs down to bedrock and crashed game.  Also does it when asked to clear a room.  When asked to light up area however, it does it with no problem.

**Comment by McJty** [comment]
Please report to sponge. This looks like a bug on their side

**Comment by Shybella** [comment]
Thanks all fixed now.
