### ISSUE TITLE
MeeCreeps stopped working on Direwolf20 1.12

### ISSUE THREAD

**Issue by realm174** [McJtyMods/MeeCreeps#55]
Hello,
I have a somewhat customized Direwolf20 pack I'm playing. (I've removed a bunch of mods, and added MineColonies).  Everything worked well, until the first MineColonist spawned.  From that moment on, I can spawn MeeCreeps, but they just stand idle, not doing anything. I read a few bug reports regarding FTBUtilities and Fake Players, and claimed chunks.. I did have some claimed chunks, but unclaimed them since. No improvement. So I disabled FTBUtilities completely from the server and client, and same thing. I can spawn the Creeps, but they don't do any work. Any other suggestion?

**Comment by McJty** [comment]
MineColonies is also interphering with the RFTools Builder. I suspect this is a bug on their side

**Comment by realm174** [comment]
Good to know.   After posting the above. I came across this: https://github.com/ldtteam/minecolonies/issues/2471

Is it possible that there is a typo somewhere in code where MeeCreeps is spelled wrong? (MeeCreps, missing one e) ?  I have a feeling that this is where MineColonies is preventing the MeeCreep to work.

**Comment by gjp** [comment]
@realm174 Here? (very end of the line)

https://github.com/McJtyMods/MeeCreeps/blob/d3541e508a95d562092d4ea19831e23ff3363291/src/main/java/mcjty/meecreeps/varia/GeneralTools.java#L25

**Comment by realm174** [comment]
Looks like it.. so now I guess we wait for the next release ?  Good job finding it ! :)

**Comment by McJty** [comment]
I will fix this for next release

**Comment by realm174** [comment]
Much appreciated, thanks!!

**Comment by McJty** [comment]
I just released MeeCreeps 1.2.2 which might possibly fix this. If it doesn't then the issue is most likely on MineColonies side. The release is awaiting approving
