### ISSUE TITLE
MeeCreeps stop working using Minecolonies

### ISSUE THREAD

**Issue by zedace** [McJtyMods/MeeCreeps#57]
Started a new world and was using MeeCreeps - able to clear areas, remove trees, build structures, etc.  After crafting a supply camp for MineColonies, the MeeCreeps won't perform any actions at all.

**Comment by McJty** [comment]
I just released MeeCreeps 1.2.2 which might possibly fix this. If it doesn't then the issue is most likely on MineColonies side. The release is awaiting approving
