### ISSUE TITLE
server and game crash when meecreaps attemps to chop burned tree

### ISSUE THREAD

**Issue by Mikecolle** [McJtyMods/MeeCreeps#65]
game crashes when attempting to have meecreaps chop down a tree that had parts previously;y on fire

[crash-2018-10-28_22.22.25-server.txt](https://github.com/McJtyMods/MeeCreeps/files/2523980/crash-2018-10-28_22.22.25-server.txt)

**Comment by McJty** [comment]
I added protection for this for the next version
