### ISSUE TITLE
Crash when meecreeps is spawned

### ISSUE THREAD

**Issue by luisantonio98** [McJtyMods/MeeCreeps#66]
When I spawn Mr. Meecreeps the game freezes then promptly crashes.
Crash: [crash-2018-10-30_13.03.08-client.txt](https://github.com/McJtyMods/MeeCreeps/files/2531444/crash-2018-10-30_13.03.08-client.txt)

**Comment by McJty** [comment]
This is an extremely outdated version of meecreeps
