### ISSUE TITLE
Server crash using portal gun (sponge)

### ISSUE THREAD

**Issue by krisjenner** [McJtyMods/MeeCreeps#67]
Crash log: https://gist.github.com/krisjenner/bae395611f68162921e07aad8aeab095

Sponge 7.1.6RC3616
MeeCreeps 1.2.3

**Comment by krisjenner** [comment]
https://gist.github.com/krisjenner/798a5c08f8137849dfd6e38ce02f565e

**Comment by McJty** [comment]
I can add protection for this but can you describe to me when this happened exactly? What were you doing?

**Comment by krisjenner** [comment]
Hey! Sorry I actually realised it was a combination of the portal tile entity and the Watch of Flowing time from ProjectE on a DM Pedestal speeding it up that caused the crash. The entity can be blacklisted from the watch in ProjectE config.

In short: it wasn't your mod

Thanks anyway <3
