### ISSUE TITLE
MeeCreeps forgot how to do things

### ISSUE THREAD

**Issue by scottstubbs** [McJtyMods/MeeCreeps#68]
The MeeCreeps are telling me "There is not much I can do here" when I right-click them on a block. This didn't start until I upgraded the mod from 1.12-1.2.3 to 1.12-1.3.0. Attaching a screenshot, the custom profile with versions of forge, etc. Last attachment is latest log file.

Screenshot
![2019-05-04_21 01 12](https://user-images.githubusercontent.com/12249/57187165-d9452e80-6eb0-11e9-9910-adb0e309cdea.png)

Custom Profile
![MeeCreeps-Versions](https://user-images.githubusercontent.com/12249/57187171-f0841c00-6eb0-11e9-8584-b8e2a59abb59.PNG)

[Latest Logfile](https://github.com/McJtyMods/MeeCreeps/files/3145056/latest.log)

**Comment by McJty** [comment]
I'll check this out now

**Comment by McJty** [comment]
I found the issue. Will be fixed next release (very soon)
